<a href="https://colab.research.google.com/github/praksb2428-maker/Deep.practice/blob/main/2026_04_07_2nd_Deep_Learning_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from google.colab import drive # 코랩과 구글 드라이브를 연결하는 기능
drive.mount('/content/drive') # 내 구글드라이브와 연결

windowed_dattase = pd.read_csv('/content/drive/MyDrive/DailyDelhiClimateTest.csv') # pd 라는 함수를 사용하여 내 구글드라이브에 있는 csv 파일을 읽음
windowed_dattase.head() # 상위 5개를 출력

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

         date   meantemp   humidity  wind_speed  meanpressure
0  2017-01-01  15.913043  85.869565    2.743478     59.000000
1  2017-01-02  18.500000  77.222222    2.894444   1018.277778
2  2017-01-03  17.111111  81.888889    4.016667   1018.333333
3  2017-01-04  18.700000  70.050000    4.545000   1015.700000
4  2017-01-05  18.388889  74.944444    3.300000   1014.333333

코랩과 구글드라이브를 연결하는 기능을 사용하여 내 구글드라이브에 업로드한 csv 데이터를 코랩에 가져와 상위5개를 출력

In [ ]:
# 데이터 크기
print(f" 행,열: {df.shape}")
print(f" 행 수: {df.shape[0]:,}")
print(f" 열 수: {df.shape[1]}")
print(f" 총 개수: {df.size:,}")

 행,열: (114, 5)
 행 수: 114
 열 수: 5
 총 개수: 570

csv 데이터의 행열, 행, 열, 총 수를 출력

In [ ]:
# 데이터 사전
def create_fixed_dictionary(df, columns):
    data_dict = pd.DataFrame({

        '컬럼명': columns,
        '데이터타입': [df[col].dtype for col in columns],
        '고유값수': [df[col].nunique() for col in columns],
        '샘플값': [str(df[col].iloc[0]) for col in columns],
        '설명': [
            '📅 관측일자 (YYYY-MM-DD)',
            '🌡️ 평균기온 (°C)',
            '💧 상대습도 (%)',
            '💨 풍속 (km/h)',
            '⛅ 평균기압 (hPa)'
        ][:len(columns)]
    })
    return data_dict

display(data_dict)

            컬럼명    데이터타입  고유값수          샘플값                   설명
0          date   object   114   2017-01-01  📅 관측일자 (YYYY-MM-DD)
1      meantemp  float64   105  15.91304348         🌡️ 평균기온 (°C)
2      humidity  float64   109  85.86956522           💧 상대습도 (%)
3    wind_speed  float64   107  2.743478261          💨 풍속 (km/h)
4  meanpressure  float64   109         59.0         ⛅ 평균기압 (hPa)

컬렴명 순서는 csv파일 데이터의 열의 수서대로 대입이 되었다. 데이터타입이 object와 float64 두 종류인 이유는 샘플값이 부동소수점을 출력했기에 float64로 표기가 되었고 date가 숫자열이 아닌 문자열로 인식이 되었기에 object라 표기됨. 각각 meantemp, humidity, wind_speed, meanpressure 은 설명에 맞게 평균기온, 습도, 풍속, 평균기압 으로 표기되었음